import type { Metadata } from "next";
import localFont from "next/font/local";
import {
  Inter,
  Roboto,
  Lora,
  Poppins,
  Montserrat,
  Dancing_Script,
} from "next/font/google";
import "./globals.css";

const generalSans = localFont({
  src: [
    {
      path: "../public/fonts/GeneralSans-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/GeneralSans-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/GeneralSans-Italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/GeneralSans-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/GeneralSans-MediumItalic.woff2",
      weight: "500",
      style: "italic",
    },
    {
      path: "../public/fonts/GeneralSans-Semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/GeneralSans-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-generalSans",
});
export const interFont = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const dancingFont = Dancing_Script({
  subsets: ["latin"],
  weight: "700",
  variable: "--font-dancing",
});
export const robotoFont = Roboto({
  subsets: ["latin"],
  weight: "700",
  variable: "--font-roboto",
});
export const loraFont = Lora({ subsets: ["latin"], variable: "--font-lora" });
export const poppinsFont = Poppins({
  subsets: ["latin"],
  weight: "600",
  variable: "--font-poppins",
});
export const montserratFont = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});
const ttNorms = localFont({
  src: [
    {
      path: "../public/fonts/TTNormsPro-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-ttNorms",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${generalSans.variable} ${ttNorms.variable} ${dancingFont.variable} ${interFont.variable} ${robotoFont.variable} ${loraFont.variable} ${poppinsFont.variable} ${montserratFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
